version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: receipt-processor-challenge
    ports:
      - "80:80"
    volumes:
      - .:/app
      - /app/__pycache__
    environment:
      - PYTHONBUFFERED=1
    command: ["sh", "-c", "python -m pytest tests/ --maxfail=1 --disable-warnings && python -m uvicorn src.receipts.main:app --host 0.0.0.0 --port 80"]